language: node_js
sudo: 'false'
before_script: []
env:
  global:
    - secure: >-
        kUz9dFmR0N5teUp32Y3qbYVJaW9Lslh5mn8tKUgKZudY296JVzM907jsKJ/sbhg1Qp85eau43hM4va4qFSUweBsqGL5e6DRB1tX7BARYIJ1z4CcWIYjRTPa2cS53oc/ECGCH4Xvx6la0c3bOAojAickxXaOuVs1eiyGS4ebwcTiIUg7V9P3NdS92wCxa6wQhUecM1YWsN94i73VrZmhWlCzRRLYJsRe7t8q5slsNc6ajUeFMevp/wpw/jT40RXkIrym5NzpXaLT4Pn9S6IjK/n1d4Zlozx6MG0Tc70hIiaaeXQt2mg3y4zamDmIYbgP+y1uuYtZ3zz2kAqrKuDIFL+2zfG9Y2SA4eouMfw+ugqVgPsyfCmKenG6W9EDWKGUdqsKDOooUT/YMPhkFd6ZE2GGmsrPRMvfVHP+YPFkWvFh3mIiVO/6zl9V0ZzaGxbj0Ms/hYJJmiD3hLjasnVZYJfoF+/CuAj+itvWpBOMVpcsbjcn68tdiwQjtGUkeD/CPlMnnyowxW6c5Gd2gx/KW79hKp+3fPXeo/+AQUdrli8QDZcVLKv/cSs6qc7VWU6aVFRNt7rflmdBBkVCO/0UNminpJy6hcb19T/sgXTh8vm2EB6f+X3s0vQd7QA9f3NXh6smKSnqmkWiZSEwrVQ3BN3WElsJg2MK4cYQ9cc1y0Qw=
    - secure: >-
        q1U+ELJibQUWQTuiZ3Ps5ulK3S+YqnGofcVY5SPN0u+XzF4LNogmxvR8lQvruxkM58NfgBTwVWYgpr1CGJ750IfFUISnhLMRkLi/zJl/LLzWwaARKWtcF3ToxBo0VZZO1QqB0xRW3Vn3W9oqEQOEb1hl8UU4T4C1wO5cEgUrIsGS0oHAUHrgFtQPbNsYugPWbygh+VCypjju/tEFucvRGRU3HRevpANLFAivtWM4sevcAEX3cW6DEV20CSJ63yv5eAWwPUSzrj+4NVRQdhxL8UPoNBoP4sKSOLJguK1coD3UBeYToaSRqBqtjK6oO5Nv8Wb6Rylfm0JApkT9BoyNkgZoyWXhc+Cfw2DrODxd3MYtI1g0toXRIxb+XIwtUj1QeyWzVDde0mEti16oG9Tll1qWxNAKZa5t0j/4gNM+EOUk5TWB2KYOwTZMbXcEpytvMCxjq0PQm4EUsDp6NQnpjCl4Faxk072+D56ttSWYg4RT03MbBwoqO9wV8p68z0rbd4Gx6f5QrKUK0s+qesasJ0wf4uuUDVBuoWnA8KvPJNsyJUdWy6DIDJuKHy0aUAoEVk0U+kpx2/+ouvxbV0SjG6U1MycP4xrYyHeomJq4zm1Bjsfs3wKi+GQknqm3xU26eowAqHLlsfD1PnYjlxcnw5QtQnChoMqa93gpvUHwLPo=
node_js: '9'
addons:
  firefox: latest
  chrome: stable
script:
  - xvfb-run polymer test
  - |-
    >-
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test -s 'default';
    fi
dist: trusty
install:
  - npm install -g polymer-cli
  - polymer install --variants
cache:
  directories:
    - node_modules
